### ISSUE TITLE
select and deselect all table entity 

### ISSUE THREAD

**Issue by aziz-access** [infra-geo-ouverte/igo2-lib#1512]
Select all doesn't work in (Measure tool, Draw tool

![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/119948730/0f5b27b3-1ff8-4133-a6ae-82c43fb2f2cb)

**Comment by MSPKarengeo** [comment]
When I finish drawing different lines and polygons and I need to select all of them, it doesn't work. I need to have selected one of them so that it recognizes it in memory and thus selects them as a group. For example, I selected the first 2 measurements one after the other, once I went to select all, the utility selected only the first two from the list. If in this case I select each and every one of the measurements one after the other, the tool in this case will select all the measurements.


![Image](https://github.com/infra-geo-ouverte/igo2-lib/assets/90481471/4fb08f75-fde2-4118-9ea0-29adbf92dd80)

**Comment by MSPKarengeo** [comment]
I made the following tests:
Insert different line measurements. Action: select and deselect all at the same time. Runs correctly
Insert different sizes of polygons. Action: select and deselect all at the same time. Runs correctly
Insert lines and polygons at the same time. Action: select and deselect all at the same time. Runs correctly.
For me now it is perfect.
