### ISSUE TITLE
Toolbar priority in sidenav

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#350]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha

In some case the toolbar is hidden by various other panels. 

![2019-06-07_12-47-52](https://user-images.githubusercontent.com/7397743/59120088-82ed6480-8922-11e9-9512-d41af494066d.gif)

**Comment by cbourget** [comment]
This is not easy to fix because a simple scrollbar would make no sense. Up/Down arrows would make a lot more sense,

Right now, the hidden tools can still be accessed by returning to the main menu.

Also, the bottom section of the sidenav might be replaced with something else in the near future, reducing the need for this feature.

For those reasons, I think this should be bumped to a further version What do you think?
