### ISSUE TITLE
Changing printing resolution (DPI) do not refresh layers 

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#57]
When you change the printing resolution, the map scale decrease and the layers are not updated before to be print. 

On the PDF output, the layers are not complete (were not refreshed)

![image](https://cloud.githubusercontent.com/assets/7397743/26215314/e6a58952-3bcd-11e7-8d78-1c506355ba8d.png)

**Comment by cbourget** [comment]
What kind of layers are those? WFS? WMS and tile layers should wait until de map is completely refreshed before printing but the same has not been done yet with WFS.

**Comment by pelord** [comment]
It is WMS layer. I'm using IGO2 from ...pregeo... with the "Données Québec" context.

**Comment by cbourget** [comment]
I'll take a look at it when I get a chance. Thanks for reporting this issue.

**Comment by cbourget** [comment]
The problem seems to be that when changing the resolution to 300PPI, the requested image size is greater than the maximum size (3200px in that case) specified in the WMS. 

See https://pregeoegl.msp.gouv.qc.ca/ws/igo_gouvouvert.fcgi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&layers=MRN_FEUX_POINT_1994_2007_P&version=1.3.0&CRS=EPSG%3A3857&STYLES=&WIDTH=4589&HEIGHT=3119&BBOX=-8741231.542853156%2C5533181.7105705105%2C-8039692.497251808%2C6009995.89301344

This value should be increased in at on the service side, if needed.

On the client side, maybe we could query multiple images but I don't think the result would be good anyway because there would be artificats near the edges (cut labels for example).
