### ISSUE TITLE
Getinfo result in panel, possibility to config in html format

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2-lib#73]
In the config app json, it should be possible to set the value result of a getfeatureinfo as HTML and with this config all wms getfeatureinfo will be shown as HTML code in the panel. This way, if for example a getfeatureinfo result has a HTML code (<a href="/adnv2/tableaux/TableauRegionSimple.php?id=274&type_rapport=BASSIN" target="_blank">Tableau des débits-niveaux des stations du bassin versant</a>) into to it, it will be shown as HTML in the GetInfo panel.

**Comment by gignacnic** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/commit/5e9ed5f56df8cccd3a52e918785a5088655220ab

**Comment by pelord** [comment]
I think managing the html format into the panel is not really possible due to various format/size and structure. 

At this time, I see few options.
1. New browser tab:

- window.open(res,'_blank'); to popup into a new tab

- window.open(res['url'], "GetInfo", "width=400,height=300"); for floating windows [Example on w3schools](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_open2)

Pros : Handle templates from any dimension, independently of the user's device. Let the web responsive design responsability to the template, not to the app. 
Cons : When opening a blank page, we leave the map.

2. Sort of overlay as: [Overlay an Plunker](http://jasonwatmore.com/post/2017/01/24/angular-2-custom-modal-window-dialog-box). 
Pros: Keep user see a part of the map
Cons: On some support (mobile, tablet), item's description could be compressed on multiple lines for large templates and long scrolling to navigate through (no web responsive design).  Freeze user's navigation.

3. OpenLayers Popup [OpenLayers demo](http://openlayers.org/en/latest/examples/popup.html?q=popup)
Pro: Intuitive
Cons: On some support (mobile, tablet), item's description could be compressed on multiple lines for large templates and long scrolling to navigate through (no web responsive design). 

Here me draft. Waiting for you comments!

**Comment by nbtetreault** [comment]
What about a popup as described, with a link to "open in a new tab". If it doesnt fit in IGO it will be working in the new tab. 

By opening it in a new tab it implies the getinfo to be accessible with a simple GET request. It will be possible to share this URL by mail, social network...
